// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Используем SQLite по умолчанию, можно переопределить через DATABASE_URL в .env
const databaseUrl = process.env["DATABASE_URL"]?.startsWith("file:")
  ? process.env["DATABASE_URL"]
  : "file:./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
